import { defineSchemaSnapshot } from "@chardb/core/server";

// Generated immutable version-2 schema snapshot and reviewed
// additive migration. Do not edit this file after deployment.
export const schemaSnapshot = defineSchemaSnapshot({
  "format": "chardb.schema-snapshot.v1",
  "version": 2,
  "name": "saml_idp",
  "previousDigest": "9ac92a1d63ea33ac842f158cac3db77d9f61f96bd51aa1cd38d7424e257b9ec7",
  "cdbTables": [
    {
      "tableName": "messages",
      "columns": [
        {
          "name": "id",
          "sql": "\"id\" text PRIMARY KEY NOT NULL"
        },
        {
          "name": "organization_id",
          "sql": "\"organization_id\" text NOT NULL"
        },
        {
          "name": "author_id",
          "sql": "\"author_id\" text NOT NULL"
        },
        {
          "name": "body",
          "sql": "\"body\" text NOT NULL"
        },
        {
          "name": "attachment",
          "sql": "\"attachment\" text"
        },
        {
          "name": "created_at",
          "sql": "\"created_at\" integer NOT NULL"
        }
      ],
      "constraints": [],
      "indexes": []
    }
  ],
  "catalogTables": [
    {
      "tableName": "account",
      "columns": [
        {
          "name": "id",
          "sql": "\"id\" text PRIMARY KEY NOT NULL"
        },
        {
          "name": "accountId",
          "sql": "\"accountId\" text NOT NULL"
        },
        {
          "name": "providerId",
          "sql": "\"providerId\" text NOT NULL"
        },
        {
          "name": "userId",
          "sql": "\"userId\" text NOT NULL"
        },
        {
          "name": "accessToken",
          "sql": "\"accessToken\" text"
        },
        {
          "name": "refreshToken",
          "sql": "\"refreshToken\" text"
        },
        {
          "name": "idToken",
          "sql": "\"idToken\" text"
        },
        {
          "name": "accessTokenExpiresAt",
          "sql": "\"accessTokenExpiresAt\" integer"
        },
        {
          "name": "refreshTokenExpiresAt",
          "sql": "\"refreshTokenExpiresAt\" integer"
        },
        {
          "name": "scope",
          "sql": "\"scope\" text"
        },
        {
          "name": "password",
          "sql": "\"password\" text"
        },
        {
          "name": "createdAt",
          "sql": "\"createdAt\" integer NOT NULL DEFAULT (unixepoch() * 1000)"
        },
        {
          "name": "updatedAt",
          "sql": "\"updatedAt\" integer NOT NULL"
        }
      ],
      "constraints": [
        {
          "kind": "unique",
          "name": "account_providerId_accountId_unique",
          "sql": "CONSTRAINT \"account_providerId_accountId_unique\" UNIQUE (\"providerId\", \"accountId\")"
        },
        {
          "kind": "foreign-key",
          "name": "account_userId_user_id_fk",
          "sql": "CONSTRAINT \"account_userId_user_id_fk\" FOREIGN KEY (\"userId\") REFERENCES \"user\" (\"id\") ON DELETE CASCADE"
        }
      ],
      "indexes": [
        {
          "name": "account_userId_idx",
          "unique": false,
          "sql": "CREATE INDEX \"account_userId_idx\" ON \"account\" (\"userId\")"
        }
      ]
    },
    {
      "tableName": "invitation",
      "columns": [
        {
          "name": "id",
          "sql": "\"id\" text PRIMARY KEY NOT NULL"
        },
        {
          "name": "organizationId",
          "sql": "\"organizationId\" text NOT NULL"
        },
        {
          "name": "email",
          "sql": "\"email\" text NOT NULL"
        },
        {
          "name": "role",
          "sql": "\"role\" text"
        },
        {
          "name": "status",
          "sql": "\"status\" text NOT NULL DEFAULT 'pending'"
        },
        {
          "name": "expiresAt",
          "sql": "\"expiresAt\" integer NOT NULL"
        },
        {
          "name": "createdAt",
          "sql": "\"createdAt\" integer NOT NULL DEFAULT (unixepoch() * 1000)"
        },
        {
          "name": "inviterId",
          "sql": "\"inviterId\" text NOT NULL"
        }
      ],
      "constraints": [
        {
          "kind": "foreign-key",
          "name": "invitation_organizationId_organization_id_fk",
          "sql": "CONSTRAINT \"invitation_organizationId_organization_id_fk\" FOREIGN KEY (\"organizationId\") REFERENCES \"organization\" (\"id\")"
        },
        {
          "kind": "foreign-key",
          "name": "invitation_inviterId_user_id_fk",
          "sql": "CONSTRAINT \"invitation_inviterId_user_id_fk\" FOREIGN KEY (\"inviterId\") REFERENCES \"user\" (\"id\")"
        }
      ],
      "indexes": [
        {
          "name": "invitation_email_idx",
          "unique": false,
          "sql": "CREATE INDEX \"invitation_email_idx\" ON \"invitation\" (\"email\")"
        },
        {
          "name": "invitation_organizationId_idx",
          "unique": false,
          "sql": "CREATE INDEX \"invitation_organizationId_idx\" ON \"invitation\" (\"organizationId\")"
        }
      ]
    },
    {
      "tableName": "jwks",
      "columns": [
        {
          "name": "id",
          "sql": "\"id\" text PRIMARY KEY NOT NULL"
        },
        {
          "name": "publicKey",
          "sql": "\"publicKey\" text NOT NULL"
        },
        {
          "name": "privateKey",
          "sql": "\"privateKey\" text NOT NULL"
        },
        {
          "name": "createdAt",
          "sql": "\"createdAt\" integer NOT NULL"
        },
        {
          "name": "expiresAt",
          "sql": "\"expiresAt\" integer"
        },
        {
          "name": "alg",
          "sql": "\"alg\" text"
        },
        {
          "name": "crv",
          "sql": "\"crv\" text"
        }
      ],
      "constraints": [],
      "indexes": []
    },
    {
      "tableName": "member",
      "columns": [
        {
          "name": "id",
          "sql": "\"id\" text PRIMARY KEY NOT NULL"
        },
        {
          "name": "organizationId",
          "sql": "\"organizationId\" text NOT NULL"
        },
        {
          "name": "userId",
          "sql": "\"userId\" text NOT NULL"
        },
        {
          "name": "role",
          "sql": "\"role\" text NOT NULL DEFAULT 'member'"
        },
        {
          "name": "createdAt",
          "sql": "\"createdAt\" integer NOT NULL"
        }
      ],
      "constraints": [
        {
          "kind": "unique",
          "name": "member_organizationId_userId_unique",
          "sql": "CONSTRAINT \"member_organizationId_userId_unique\" UNIQUE (\"organizationId\", \"userId\")"
        },
        {
          "kind": "foreign-key",
          "name": "member_organizationId_organization_id_fk",
          "sql": "CONSTRAINT \"member_organizationId_organization_id_fk\" FOREIGN KEY (\"organizationId\") REFERENCES \"organization\" (\"id\")"
        },
        {
          "kind": "foreign-key",
          "name": "member_userId_user_id_fk",
          "sql": "CONSTRAINT \"member_userId_user_id_fk\" FOREIGN KEY (\"userId\") REFERENCES \"user\" (\"id\")"
        }
      ],
      "indexes": [
        {
          "name": "member_organizationId_idx",
          "unique": false,
          "sql": "CREATE INDEX \"member_organizationId_idx\" ON \"member\" (\"organizationId\")"
        },
        {
          "name": "member_userId_idx",
          "unique": false,
          "sql": "CREATE INDEX \"member_userId_idx\" ON \"member\" (\"userId\")"
        }
      ]
    },
    {
      "tableName": "organization",
      "columns": [
        {
          "name": "id",
          "sql": "\"id\" text PRIMARY KEY NOT NULL"
        },
        {
          "name": "name",
          "sql": "\"name\" text NOT NULL"
        },
        {
          "name": "slug",
          "sql": "\"slug\" text NOT NULL CONSTRAINT \"organization_slug_unique\" UNIQUE"
        },
        {
          "name": "logo",
          "sql": "\"logo\" text"
        },
        {
          "name": "createdAt",
          "sql": "\"createdAt\" integer NOT NULL"
        },
        {
          "name": "metadata",
          "sql": "\"metadata\" text"
        }
      ],
      "constraints": [],
      "indexes": [
        {
          "name": "organization_slug_idx",
          "unique": false,
          "sql": "CREATE INDEX \"organization_slug_idx\" ON \"organization\" (\"slug\")"
        }
      ]
    },
    {
      "tableName": "samlIdpAuditEvent",
      "columns": [
        {
          "name": "id",
          "sql": "\"id\" text PRIMARY KEY NOT NULL"
        },
        {
          "name": "type",
          "sql": "\"type\" text NOT NULL"
        },
        {
          "name": "at",
          "sql": "\"at\" integer NOT NULL"
        },
        {
          "name": "spId",
          "sql": "\"spId\" text"
        },
        {
          "name": "userId",
          "sql": "\"userId\" text"
        },
        {
          "name": "code",
          "sql": "\"code\" text"
        },
        {
          "name": "ipAddress",
          "sql": "\"ipAddress\" text"
        },
        {
          "name": "userAgent",
          "sql": "\"userAgent\" text"
        },
        {
          "name": "details",
          "sql": "\"details\" text NOT NULL"
        },
        {
          "name": "expiresAt",
          "sql": "\"expiresAt\" integer NOT NULL"
        },
        {
          "name": "tenantId",
          "sql": "\"tenantId\" text"
        }
      ],
      "constraints": [],
      "indexes": [
        {
          "name": "samlIdpAuditEvent_at_idx",
          "unique": false,
          "sql": "CREATE INDEX \"samlIdpAuditEvent_at_idx\" ON \"samlIdpAuditEvent\" (\"at\")"
        },
        {
          "name": "samlIdpAuditEvent_expiresAt_idx",
          "unique": false,
          "sql": "CREATE INDEX \"samlIdpAuditEvent_expiresAt_idx\" ON \"samlIdpAuditEvent\" (\"expiresAt\")"
        },
        {
          "name": "samlIdpAuditEvent_spId_idx",
          "unique": false,
          "sql": "CREATE INDEX \"samlIdpAuditEvent_spId_idx\" ON \"samlIdpAuditEvent\" (\"spId\")"
        },
        {
          "name": "samlIdpAuditEvent_tenantId_idx",
          "unique": false,
          "sql": "CREATE INDEX \"samlIdpAuditEvent_tenantId_idx\" ON \"samlIdpAuditEvent\" (\"tenantId\")"
        },
        {
          "name": "samlIdpAuditEvent_type_idx",
          "unique": false,
          "sql": "CREATE INDEX \"samlIdpAuditEvent_type_idx\" ON \"samlIdpAuditEvent\" (\"type\")"
        },
        {
          "name": "samlIdpAuditEvent_userId_idx",
          "unique": false,
          "sql": "CREATE INDEX \"samlIdpAuditEvent_userId_idx\" ON \"samlIdpAuditEvent\" (\"userId\")"
        }
      ]
    },
    {
      "tableName": "samlIdpRetiredTenantKey",
      "columns": [
        {
          "name": "id",
          "sql": "\"id\" text PRIMARY KEY NOT NULL"
        },
        {
          "name": "tenantKey",
          "sql": "\"tenantKey\" text NOT NULL CONSTRAINT \"samlIdpRetiredTenantKey_tenantKey_unique\" UNIQUE"
        },
        {
          "name": "organizationId",
          "sql": "\"organizationId\" text NOT NULL"
        },
        {
          "name": "retiredAt",
          "sql": "\"retiredAt\" integer NOT NULL"
        },
        {
          "name": "retiredBy",
          "sql": "\"retiredBy\" text"
        }
      ],
      "constraints": [],
      "indexes": []
    },
    {
      "tableName": "samlIdpSeenRequest",
      "columns": [
        {
          "name": "id",
          "sql": "\"id\" text PRIMARY KEY NOT NULL"
        },
        {
          "name": "key",
          "sql": "\"key\" text NOT NULL CONSTRAINT \"samlIdpSeenRequest_key_unique\" UNIQUE"
        },
        {
          "name": "spId",
          "sql": "\"spId\" text NOT NULL"
        },
        {
          "name": "requestId",
          "sql": "\"requestId\" text NOT NULL"
        },
        {
          "name": "expiresAt",
          "sql": "\"expiresAt\" integer NOT NULL"
        }
      ],
      "constraints": [],
      "indexes": [
        {
          "name": "samlIdpSeenRequest_expiresAt_idx",
          "unique": false,
          "sql": "CREATE INDEX \"samlIdpSeenRequest_expiresAt_idx\" ON \"samlIdpSeenRequest\" (\"expiresAt\")"
        }
      ]
    },
    {
      "tableName": "samlIdpServiceProvider",
      "columns": [
        {
          "name": "id",
          "sql": "\"id\" text PRIMARY KEY NOT NULL"
        },
        {
          "name": "spId",
          "sql": "\"spId\" text NOT NULL CONSTRAINT \"samlIdpServiceProvider_spId_unique\" UNIQUE"
        },
        {
          "name": "entityId",
          "sql": "\"entityId\" text NOT NULL"
        },
        {
          "name": "config",
          "sql": "\"config\" text NOT NULL"
        },
        {
          "name": "enabled",
          "sql": "\"enabled\" integer NOT NULL"
        },
        {
          "name": "createdAt",
          "sql": "\"createdAt\" integer NOT NULL"
        },
        {
          "name": "updatedAt",
          "sql": "\"updatedAt\" integer NOT NULL"
        },
        {
          "name": "updatedBy",
          "sql": "\"updatedBy\" text"
        },
        {
          "name": "tenantId",
          "sql": "\"tenantId\" text NOT NULL DEFAULT ''"
        },
        {
          "name": "lookupKey",
          "sql": "\"lookupKey\" text NOT NULL CONSTRAINT \"samlIdpServiceProvider_lookupKey_unique\" UNIQUE"
        }
      ],
      "constraints": [],
      "indexes": [
        {
          "name": "samlIdpServiceProvider_entityId_idx",
          "unique": false,
          "sql": "CREATE INDEX \"samlIdpServiceProvider_entityId_idx\" ON \"samlIdpServiceProvider\" (\"entityId\")"
        },
        {
          "name": "samlIdpServiceProvider_tenantId_idx",
          "unique": false,
          "sql": "CREATE INDEX \"samlIdpServiceProvider_tenantId_idx\" ON \"samlIdpServiceProvider\" (\"tenantId\")"
        }
      ]
    },
    {
      "tableName": "samlIdpSessionParticipant",
      "columns": [
        {
          "name": "id",
          "sql": "\"id\" text PRIMARY KEY NOT NULL"
        },
        {
          "name": "key",
          "sql": "\"key\" text NOT NULL CONSTRAINT \"samlIdpSessionParticipant_key_unique\" UNIQUE"
        },
        {
          "name": "sessionKey",
          "sql": "\"sessionKey\" text NOT NULL"
        },
        {
          "name": "userId",
          "sql": "\"userId\" text"
        },
        {
          "name": "endedAt",
          "sql": "\"endedAt\" integer"
        },
        {
          "name": "spId",
          "sql": "\"spId\" text NOT NULL"
        },
        {
          "name": "nameId",
          "sql": "\"nameId\" text NOT NULL"
        },
        {
          "name": "nameIdFormat",
          "sql": "\"nameIdFormat\" text NOT NULL"
        },
        {
          "name": "sessionIndex",
          "sql": "\"sessionIndex\" text NOT NULL"
        },
        {
          "name": "expiresAt",
          "sql": "\"expiresAt\" integer NOT NULL"
        }
      ],
      "constraints": [],
      "indexes": [
        {
          "name": "samlIdpSessionParticipant_expiresAt_idx",
          "unique": false,
          "sql": "CREATE INDEX \"samlIdpSessionParticipant_expiresAt_idx\" ON \"samlIdpSessionParticipant\" (\"expiresAt\")"
        },
        {
          "name": "samlIdpSessionParticipant_sessionKey_idx",
          "unique": false,
          "sql": "CREATE INDEX \"samlIdpSessionParticipant_sessionKey_idx\" ON \"samlIdpSessionParticipant\" (\"sessionKey\")"
        },
        {
          "name": "samlIdpSessionParticipant_userId_idx",
          "unique": false,
          "sql": "CREATE INDEX \"samlIdpSessionParticipant_userId_idx\" ON \"samlIdpSessionParticipant\" (\"userId\")"
        }
      ]
    },
    {
      "tableName": "samlIdpTenant",
      "columns": [
        {
          "name": "id",
          "sql": "\"id\" text PRIMARY KEY NOT NULL"
        },
        {
          "name": "organizationId",
          "sql": "\"organizationId\" text NOT NULL CONSTRAINT \"samlIdpTenant_organizationId_unique\" UNIQUE"
        },
        {
          "name": "tenantKey",
          "sql": "\"tenantKey\" text NOT NULL CONSTRAINT \"samlIdpTenant_tenantKey_unique\" UNIQUE"
        },
        {
          "name": "organizationCreatedAt",
          "sql": "\"organizationCreatedAt\" integer NOT NULL"
        },
        {
          "name": "enabled",
          "sql": "\"enabled\" integer NOT NULL"
        },
        {
          "name": "createdAt",
          "sql": "\"createdAt\" integer NOT NULL"
        },
        {
          "name": "updatedAt",
          "sql": "\"updatedAt\" integer NOT NULL"
        },
        {
          "name": "updatedBy",
          "sql": "\"updatedBy\" text"
        }
      ],
      "constraints": [],
      "indexes": []
    },
    {
      "tableName": "samlIdpTenantKey",
      "columns": [
        {
          "name": "id",
          "sql": "\"id\" text PRIMARY KEY NOT NULL"
        },
        {
          "name": "tenantId",
          "sql": "\"tenantId\" text NOT NULL"
        },
        {
          "name": "kid",
          "sql": "\"kid\" text NOT NULL"
        },
        {
          "name": "state",
          "sql": "\"state\" text NOT NULL"
        },
        {
          "name": "stateKey",
          "sql": "\"stateKey\" text NOT NULL CONSTRAINT \"samlIdpTenantKey_stateKey_unique\" UNIQUE"
        },
        {
          "name": "encryptedPrivateKey",
          "sql": "\"encryptedPrivateKey\" text NOT NULL"
        },
        {
          "name": "certificate",
          "sql": "\"certificate\" text NOT NULL"
        },
        {
          "name": "notAfter",
          "sql": "\"notAfter\" integer NOT NULL"
        },
        {
          "name": "createdAt",
          "sql": "\"createdAt\" integer NOT NULL"
        },
        {
          "name": "activatedAt",
          "sql": "\"activatedAt\" integer"
        },
        {
          "name": "updatedBy",
          "sql": "\"updatedBy\" text"
        }
      ],
      "constraints": [],
      "indexes": [
        {
          "name": "samlIdpTenantKey_tenantId_idx",
          "unique": false,
          "sql": "CREATE INDEX \"samlIdpTenantKey_tenantId_idx\" ON \"samlIdpTenantKey\" (\"tenantId\")"
        }
      ]
    },
    {
      "tableName": "session",
      "columns": [
        {
          "name": "id",
          "sql": "\"id\" text PRIMARY KEY NOT NULL"
        },
        {
          "name": "expiresAt",
          "sql": "\"expiresAt\" integer NOT NULL"
        },
        {
          "name": "token",
          "sql": "\"token\" text NOT NULL CONSTRAINT \"session_token_unique\" UNIQUE"
        },
        {
          "name": "createdAt",
          "sql": "\"createdAt\" integer NOT NULL DEFAULT (unixepoch() * 1000)"
        },
        {
          "name": "updatedAt",
          "sql": "\"updatedAt\" integer NOT NULL"
        },
        {
          "name": "ipAddress",
          "sql": "\"ipAddress\" text"
        },
        {
          "name": "userAgent",
          "sql": "\"userAgent\" text"
        },
        {
          "name": "userId",
          "sql": "\"userId\" text NOT NULL"
        },
        {
          "name": "activeOrganizationId",
          "sql": "\"activeOrganizationId\" text"
        }
      ],
      "constraints": [
        {
          "kind": "foreign-key",
          "name": "session_userId_user_id_fk",
          "sql": "CONSTRAINT \"session_userId_user_id_fk\" FOREIGN KEY (\"userId\") REFERENCES \"user\" (\"id\") ON DELETE CASCADE"
        }
      ],
      "indexes": [
        {
          "name": "session_userId_idx",
          "unique": false,
          "sql": "CREATE INDEX \"session_userId_idx\" ON \"session\" (\"userId\")"
        }
      ]
    },
    {
      "tableName": "user",
      "columns": [
        {
          "name": "id",
          "sql": "\"id\" text PRIMARY KEY NOT NULL"
        },
        {
          "name": "name",
          "sql": "\"name\" text NOT NULL"
        },
        {
          "name": "email",
          "sql": "\"email\" text NOT NULL CONSTRAINT \"user_email_unique\" UNIQUE"
        },
        {
          "name": "emailVerified",
          "sql": "\"emailVerified\" integer NOT NULL DEFAULT 0"
        },
        {
          "name": "image",
          "sql": "\"image\" text"
        },
        {
          "name": "createdAt",
          "sql": "\"createdAt\" integer NOT NULL DEFAULT (unixepoch() * 1000)"
        },
        {
          "name": "updatedAt",
          "sql": "\"updatedAt\" integer NOT NULL DEFAULT (unixepoch() * 1000)"
        },
        {
          "name": "isAnonymous",
          "sql": "\"isAnonymous\" integer DEFAULT 0"
        }
      ],
      "constraints": [],
      "indexes": []
    },
    {
      "tableName": "verification",
      "columns": [
        {
          "name": "id",
          "sql": "\"id\" text PRIMARY KEY NOT NULL"
        },
        {
          "name": "identifier",
          "sql": "\"identifier\" text NOT NULL"
        },
        {
          "name": "value",
          "sql": "\"value\" text NOT NULL"
        },
        {
          "name": "expiresAt",
          "sql": "\"expiresAt\" integer NOT NULL"
        },
        {
          "name": "createdAt",
          "sql": "\"createdAt\" integer NOT NULL DEFAULT (unixepoch() * 1000)"
        },
        {
          "name": "updatedAt",
          "sql": "\"updatedAt\" integer NOT NULL DEFAULT (unixepoch() * 1000)"
        }
      ],
      "constraints": [],
      "indexes": [
        {
          "name": "verification_identifier_idx",
          "unique": false,
          "sql": "CREATE INDEX \"verification_identifier_idx\" ON \"verification\" (\"identifier\")"
        }
      ]
    }
  ],
  "resources": [
    {
      "kind": "file",
      "version": 1,
      "table": "messages",
      "column": "attachment",
      "primaryKey": "id",
      "organizationColumn": "organization_id",
      "maxSize": 5242880,
      "contentTypes": [
        "image/jpeg",
        "image/png"
      ]
    }
  ],
  "digest": "0d09c1062c179346a00ae3441d23f6173c94932feffa52628092b0413a022e95"
} as const);

export const migration = Object.freeze({
  "version": 2,
  "name": "saml_idp",
  "statements": [],
  "catalogStatements": [
    "CREATE TABLE \"samlIdpAuditEvent\" (\"id\" text PRIMARY KEY NOT NULL, \"type\" text NOT NULL, \"at\" integer NOT NULL, \"spId\" text, \"userId\" text, \"code\" text, \"ipAddress\" text, \"userAgent\" text, \"details\" text NOT NULL, \"expiresAt\" integer NOT NULL, \"tenantId\" text)",
    "CREATE INDEX \"samlIdpAuditEvent_at_idx\" ON \"samlIdpAuditEvent\" (\"at\")",
    "CREATE INDEX \"samlIdpAuditEvent_expiresAt_idx\" ON \"samlIdpAuditEvent\" (\"expiresAt\")",
    "CREATE INDEX \"samlIdpAuditEvent_spId_idx\" ON \"samlIdpAuditEvent\" (\"spId\")",
    "CREATE INDEX \"samlIdpAuditEvent_tenantId_idx\" ON \"samlIdpAuditEvent\" (\"tenantId\")",
    "CREATE INDEX \"samlIdpAuditEvent_type_idx\" ON \"samlIdpAuditEvent\" (\"type\")",
    "CREATE INDEX \"samlIdpAuditEvent_userId_idx\" ON \"samlIdpAuditEvent\" (\"userId\")",
    "CREATE TABLE \"samlIdpRetiredTenantKey\" (\"id\" text PRIMARY KEY NOT NULL, \"tenantKey\" text NOT NULL CONSTRAINT \"samlIdpRetiredTenantKey_tenantKey_unique\" UNIQUE, \"organizationId\" text NOT NULL, \"retiredAt\" integer NOT NULL, \"retiredBy\" text)",
    "CREATE TABLE \"samlIdpSeenRequest\" (\"id\" text PRIMARY KEY NOT NULL, \"key\" text NOT NULL CONSTRAINT \"samlIdpSeenRequest_key_unique\" UNIQUE, \"spId\" text NOT NULL, \"requestId\" text NOT NULL, \"expiresAt\" integer NOT NULL)",
    "CREATE INDEX \"samlIdpSeenRequest_expiresAt_idx\" ON \"samlIdpSeenRequest\" (\"expiresAt\")",
    "CREATE TABLE \"samlIdpServiceProvider\" (\"id\" text PRIMARY KEY NOT NULL, \"spId\" text NOT NULL CONSTRAINT \"samlIdpServiceProvider_spId_unique\" UNIQUE, \"entityId\" text NOT NULL, \"config\" text NOT NULL, \"enabled\" integer NOT NULL, \"createdAt\" integer NOT NULL, \"updatedAt\" integer NOT NULL, \"updatedBy\" text, \"tenantId\" text NOT NULL DEFAULT '', \"lookupKey\" text NOT NULL CONSTRAINT \"samlIdpServiceProvider_lookupKey_unique\" UNIQUE)",
    "CREATE INDEX \"samlIdpServiceProvider_entityId_idx\" ON \"samlIdpServiceProvider\" (\"entityId\")",
    "CREATE INDEX \"samlIdpServiceProvider_tenantId_idx\" ON \"samlIdpServiceProvider\" (\"tenantId\")",
    "CREATE TABLE \"samlIdpSessionParticipant\" (\"id\" text PRIMARY KEY NOT NULL, \"key\" text NOT NULL CONSTRAINT \"samlIdpSessionParticipant_key_unique\" UNIQUE, \"sessionKey\" text NOT NULL, \"userId\" text, \"endedAt\" integer, \"spId\" text NOT NULL, \"nameId\" text NOT NULL, \"nameIdFormat\" text NOT NULL, \"sessionIndex\" text NOT NULL, \"expiresAt\" integer NOT NULL)",
    "CREATE INDEX \"samlIdpSessionParticipant_expiresAt_idx\" ON \"samlIdpSessionParticipant\" (\"expiresAt\")",
    "CREATE INDEX \"samlIdpSessionParticipant_sessionKey_idx\" ON \"samlIdpSessionParticipant\" (\"sessionKey\")",
    "CREATE INDEX \"samlIdpSessionParticipant_userId_idx\" ON \"samlIdpSessionParticipant\" (\"userId\")",
    "CREATE TABLE \"samlIdpTenant\" (\"id\" text PRIMARY KEY NOT NULL, \"organizationId\" text NOT NULL CONSTRAINT \"samlIdpTenant_organizationId_unique\" UNIQUE, \"tenantKey\" text NOT NULL CONSTRAINT \"samlIdpTenant_tenantKey_unique\" UNIQUE, \"organizationCreatedAt\" integer NOT NULL, \"enabled\" integer NOT NULL, \"createdAt\" integer NOT NULL, \"updatedAt\" integer NOT NULL, \"updatedBy\" text)",
    "CREATE TABLE \"samlIdpTenantKey\" (\"id\" text PRIMARY KEY NOT NULL, \"tenantId\" text NOT NULL, \"kid\" text NOT NULL, \"state\" text NOT NULL, \"stateKey\" text NOT NULL CONSTRAINT \"samlIdpTenantKey_stateKey_unique\" UNIQUE, \"encryptedPrivateKey\" text NOT NULL, \"certificate\" text NOT NULL, \"notAfter\" integer NOT NULL, \"createdAt\" integer NOT NULL, \"activatedAt\" integer, \"updatedBy\" text)",
    "CREATE INDEX \"samlIdpTenantKey_tenantId_idx\" ON \"samlIdpTenantKey\" (\"tenantId\")"
  ]
} as const);
