// Generates src/saml/schemas.generated.ts from the unmodified upstream XSDs in schemas/.
// Transforms (the only ones):
//  1. absolute schemaLocation URLs are rewritten to local file names (no network access);
//  2. the DOCTYPE is removed from xmldsig/xenc. It references the external XMLSchema.dtd and
//     declares entities the schemas never use; the #FIXED xmlns attributes it declares are
//     already present on the <schema> element. The build asserts both facts.
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";

const FILES = {
  "saml-schema-protocol-2.0.xsd": "https://docs.oasis-open.org/security/saml/v2.0/saml-schema-protocol-2.0.xsd",
  "saml-schema-assertion-2.0.xsd": "https://docs.oasis-open.org/security/saml/v2.0/saml-schema-assertion-2.0.xsd",
  "saml-schema-metadata-2.0.xsd": "https://docs.oasis-open.org/security/saml/v2.0/saml-schema-metadata-2.0.xsd",
  "xmldsig-core-schema.xsd": "https://www.w3.org/TR/xmldsig-core/xmldsig-core-schema.xsd",
  "xenc-schema.xsd": "https://www.w3.org/TR/xmlenc-core/xenc-schema.xsd",
  "xml.xsd": "https://www.w3.org/2001/xml.xsd",
};
const LOCATIONS = {
  "http://www.w3.org/TR/2002/REC-xmldsig-core-20020212/xmldsig-core-schema.xsd": "xmldsig-core-schema.xsd",
  "http://www.w3.org/TR/2002/REC-xmlenc-core-20021210/xenc-schema.xsd": "xenc-schema.xsd",
  "http://www.w3.org/2001/xml.xsd": "xml.xsd",
};

let out = "// GENERATED by scripts/build-schemas.mjs. Do not edit.\n";
out += "// Upstream sources and SHA-256 of the unmodified files:\n";
for (const [name, url] of Object.entries(FILES)) {
  const raw = readFileSync(`schemas/${name}`, "utf8");
  out += `//   ${name}  ${createHash("sha256").update(raw).digest("hex")}  ${url}\n`;
}
out += "\nexport const SCHEMAS: Record<string, string> = {\n";
for (const name of Object.keys(FILES)) {
  let xsd = readFileSync(`schemas/${name}`, "utf8");
  for (const [from, to] of Object.entries(LOCATIONS)) {
    // xml.xsd references itself in documentation-only <import>s; leave those alone.
    if (name !== "xml.xsd") xsd = xsd.replaceAll(`schemaLocation="${from}"`, `schemaLocation="${to}"`).replaceAll(`schemaLocation='${from}'`, `schemaLocation='${to}'`);
  }
  if (/<!DOCTYPE/.test(xsd)) {
    const body = xsd.replace(/<!DOCTYPE[\s\S]*?\]>/, "");
    const entities = [...xsd.matchAll(/<!ENTITY\s+(\w+)\s/g)].map((m) => m[1]);
    for (const e of entities) if (body.includes(`&${e};`)) throw new Error(`${name}: entity &${e}; is used`);
    for (const [, prefix, uri] of xsd.matchAll(/xmlns:(\w+)\s+CDATA\s+#FIXED\s+["']([^"']+)["']/g)) {
      if (!new RegExp(`<schema[^>]*xmlns:${prefix}=["']${uri.replaceAll(".", "\\.")}["']`).test(body))
        throw new Error(`${name}: xmlns:${prefix} only declared in the DTD`);
    }
    xsd = body;
  }
  const remaining = [...xsd.matchAll(/schemaLocation=["'](https?:[^"']+)["']/g)].map((m) => m[1]);
  if (name !== "xml.xsd" && remaining.length) throw new Error(`${name}: unmapped schemaLocation ${remaining}`);
  out += `  ${JSON.stringify(name)}: ${JSON.stringify(xsd)},\n`;
}
out += "};\n";
writeFileSync("src/saml/schemas.generated.ts", out);
console.log("wrote src/saml/schemas.generated.ts");
