"""Generate the comparison outputs from scripts/comparison/data.py.

  python3 scripts/comparison/gen.py

writes docs/comparison.md, docs/comparison/index.html (GitHub Pages) and the README's
"## Roadmap" section (between the markers). Re-run after editing data.py.
"""
import html, os, re, sys
sys.path.insert(0, os.path.dirname(__file__))
from data import *
ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
esc = html.escape
SYM = {"y": "✅ Yes", "p": "🟡 Partial", "n": "❌ No", "u": "❔ Not documented", "na": "n/a"}
LABEL = {"y": "Yes", "p": "Partial", "n": "No", "u": "Not documented", "na": "n/a"}
names = {p[0]: p[1] for p in PRODUCTS}
groups = []
for g, *_ in FEATURES:
    if g not in groups: groups.append(g)

# ---------------- Markdown ----------------
md = [f"# Comparison with other SAML identity providers\n",
 f"How `better-auth-saml-idp` compares with eleven SAML 2.0 identity providers, checked against each product's official documentation (and, for the open-source ones, their source code) on **{CHECKED}**. "
 "**Not documented** means the research found no statement either way; it is not the same as *no*. SaaS products are *n/a* for self-hosting rows.\n",
 "Our own column links to the tests that prove each entry. The roadmap derived from this comparison is in the [README](../README.md#-roadmap).\n",
 "## Where we lead\n"] + [f"- **{t}.** {d}" for t, d in LEADS] + ["\n## Where we trail\n"] + [f"- **{t}.** {d}" for t, d in TRAILS] + ["\n## Feature matrix\n"]
md.append("Products: " + "; ".join(f"**{p[1]}** ({p[2]}, {p[3]})" for p in PRODUCTS) + ".\n")
for g in groups:
    md.append(f"### {g}\n")
    md.append("| Feature | " + " | ".join(names[k] for k in K) + " |")
    md.append("|---|" + "---|" * len(K))
    for fg, feat, vals, ev in FEATURES:
        if fg != g: continue
        cells = []
        for k in K:
            s, note = vals[k]
            txt = note if s == "t" else SYM[s] + (f"<br><sub>{note}</sub>" if note else "")
            cells.append(txt)
        md.append(f"| {feat} | " + " | ".join(cells) + " |")
    md.append("")
md.append("## Our evidence\n")
for fg, feat, vals, ev in FEATURES:
    if ev: md.append(f"- **{feat}:** `{ev}`" if "/" in ev and "," not in ev else f"- **{feat}:** {ev}")
md.append("\n## HubSpot's requirements\n\nFrom [HubSpot's SSO setup guide](https://knowledge.hubspot.com/account-security/set-up-single-sign-on-sso):\n")
md += [f"- **{t}:** {d}" for t, d in HUBSPOT]
md.append("\n## Sources\n")
for k, n, g, v, src in PRODUCTS:
    md.append(f"- **{n}** ({v}): " + ", ".join(f"[{t}]({u})" for t, u in src))
md.append(f"\nResearch method: three parallel reviews of vendor documentation (and source code where the docs were silent), {CHECKED}. Corrections welcome as issues or pull requests.\n")
open(os.path.join(ROOT, "docs/comparison.md"), "w").write("\n".join(md) + "\n")

# ---------------- README roadmap ----------------
rm = ["## 🧭 Roadmap\n", f"Derived from a [feature comparison](https://mmcintosh.github.io/better-auth-saml-idp/comparison/) with eleven other SAML identity providers (checked {CHECKED}).\n"]
for ver, title, sub, items in ROADMAP:
    rm.append(f"**{ver}: {title}**\n")
    for t, d in items:
        done = "(done)" in t
        name = t.replace(" (done)", "")
        if ver == "Not planned":
            rm.append(f"- 🚫 **{name}**: {d}")
        else:
            rm.append(f"- [{'x' if done else ' '}] **{name}**: {d}")
    rm.append("")
readme_path = os.path.join(ROOT, "README.md")
readme = open(readme_path).read()
block = "<!-- roadmap:start (generated by scripts/comparison/gen.py) -->\n" + "\n".join(rm).strip() + "\n<!-- roadmap:end -->"
if "<!-- roadmap:start" in readme:
    readme = re.sub(r"<!-- roadmap:start.*?<!-- roadmap:end -->", lambda m: block, readme, flags=re.S)
else:
    readme = re.sub(r"## Roadmap\n.*?(?=\n## Security)", lambda m: block + "\n", readme, flags=re.S)
open(readme_path, "w").write(readme)

# ---------------- HTML ----------------
def chip(s, note):
    if s == "t": return f'<span class="txt">{esc(note)}</span>'
    n = f'<span class="note">{esc(note)}</span>' if note else ""
    return f'<span class="chip s-{s}"><i aria-hidden="true"></i>{LABEL[s]}</span>{n}'
head_groups = []
for k, n, g, v, src in PRODUCTS:
    if head_groups and head_groups[-1][0] == g: head_groups[-1][1] += 1
    else: head_groups.append([g, 1])
rows = []
for g in groups:
    rows.append(f'<tr class="grp"><th scope="rowgroup" colspan="{len(K)+1}">{esc(g)}</th></tr>')
    for fg, feat, vals, ev in FEATURES:
        if fg != g: continue
        tds = "".join(f'<td class="{"us" if k=="us" else ""}">{chip(*vals[k])}</td>' for k in K)
        rows.append(f'<tr><th scope="row">{esc(feat)}</th>{tds}</tr>')
count = {s: sum(1 for f in FEATURES if f[2]["us"][0]==s) for s in "ypn"}
roadmap_html = "".join(
  f'<section class="lane lane-{i}"><header><span class="ver">{esc(v)}</span><h3>{esc(t)}</h3><p>{esc(sub)}</p></header><ul>' +
  "".join(f'<li><strong>{esc(a)}</strong><span>{esc(b)}</span></li>' for a, b in items) + "</ul></section>"
  for i, (v, t, sub, items) in enumerate(ROADMAP))
sources_html = "".join(f'<li><strong>{esc(n)}</strong> <span class="ver-note">{esc(v)}</span><br>' + " · ".join(f'<a href="{esc(u)}">{esc(t)}</a>' for t, u in src) + "</li>" for k, n, g, v, src in PRODUCTS)
page = f'''<title>SAML IdP Landscape</title>
<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@400;500&family=IBM+Plex+Sans+Condensed:wght@500;600&family=IBM+Plex+Sans:wght@400;500;600&display=swap">
<style>
:root{{--ground:#f3f5f8;--surface:#ffffff;--ink:#17212d;--muted:#5a6676;--line:#dbe1e8;--accent:#2d5b86;--accent-soft:#e7eef6;
--yes:#1c7447;--yes-bg:#e3f2ea;--part:#99620a;--part-bg:#fbf0dc;--no:#a8323a;--no-bg:#f8e4e5;--unk:#6b7685;--unk-bg:#eceff3;--na:#8b95a3;
--sans:"IBM Plex Sans",system-ui,-apple-system,"Segoe UI",sans-serif;--cond:"IBM Plex Sans Condensed","IBM Plex Sans",system-ui,sans-serif;--mono:"IBM Plex Mono",ui-monospace,SFMono-Regular,Menlo,monospace}}
@media (prefers-color-scheme:dark){{:root:not([data-theme="light"]){{color-scheme:dark;--ground:#0e131a;--surface:#151c25;--ink:#e4e9ef;--muted:#9aa6b4;--line:#27313d;--accent:#86b4e0;--accent-soft:#1a2735;
--yes:#6fd19c;--yes-bg:#15301f;--part:#e8b35a;--part-bg:#33270f;--no:#f08a8f;--no-bg:#361a1c;--unk:#a3adba;--unk-bg:#1f2731;--na:#7c8795}}}}
:root[data-theme="dark"]{{color-scheme:dark;--ground:#0e131a;--surface:#151c25;--ink:#e4e9ef;--muted:#9aa6b4;--line:#27313d;--accent:#86b4e0;--accent-soft:#1a2735;
--yes:#6fd19c;--yes-bg:#15301f;--part:#e8b35a;--part-bg:#33270f;--no:#f08a8f;--no-bg:#361a1c;--unk:#a3adba;--unk-bg:#1f2731;--na:#7c8795}}
body{{background:var(--ground);color:var(--ink);font:15px/1.55 var(--sans)}}
.wrap{{max-width:1180px;margin:0 auto;padding-inline:20px;padding-block:32px 56px;display:grid;gap:36px}}
h1,h2,h3{{font-family:var(--cond);text-wrap:balance;margin:0;line-height:1.15}}
h1{{font-size:clamp(28px,4.2vw,40px);font-weight:600;letter-spacing:-.01em}}
h2{{font-size:22px;font-weight:600}}
.eyebrow{{font:500 12px/1 var(--mono);letter-spacing:.08em;text-transform:uppercase;color:var(--accent)}}
.lede{{max-width:68ch;color:var(--muted);margin:10px 0 0}}
.meta{{font:13px var(--mono);color:var(--muted);display:flex;flex-wrap:wrap;gap:6px 18px;margin-top:14px}}
.split{{display:grid;grid-template-columns:repeat(auto-fit,minmax(300px,1fr));gap:16px;align-items:start}}
.panel{{background:var(--surface);border:1px solid var(--line);border-radius:10px;padding:18px 20px}}
.panel h2{{font-size:18px;margin-bottom:10px}}
.panel ul{{margin:0;padding-left:18px;display:grid;gap:8px}}
.panel li strong{{display:block}}
.lead{{border-top:3px solid var(--yes)}} .trail{{border-top:3px solid var(--part)}}
.score{{display:flex;gap:10px;flex-wrap:wrap;margin-top:12px;font:13px var(--mono);color:var(--muted)}}
.legend{{display:flex;flex-wrap:wrap;gap:8px 14px;align-items:center;font-size:13px;color:var(--muted)}}
.tablebox{{overflow-x:auto;background:var(--surface);border:1px solid var(--line);border-radius:10px}}
table{{border-collapse:separate;border-spacing:0;min-width:1320px;width:100%;font-size:13px}}
thead th{{position:sticky;top:0;background:var(--surface);z-index:2}}
th,td{{padding:9px 10px;text-align:left;vertical-align:top;border-bottom:1px solid var(--line)}}
thead tr.g th{{font:500 11px var(--mono);letter-spacing:.06em;text-transform:uppercase;color:var(--muted);border-bottom:none;padding-bottom:0}}
thead tr.p th{{font:600 13px var(--cond);min-width:92px}}
thead tr.p th .v{{display:block;font:400 11px var(--mono);color:var(--muted)}}
tbody th[scope=row],thead th:first-child{{position:sticky;left:0;background:var(--surface);z-index:1;min-width:190px;max-width:220px;font-weight:500}}
thead th:first-child{{z-index:3}}
tr.grp th{{background:var(--accent-soft);color:var(--accent);font:600 12px var(--mono);letter-spacing:.06em;text-transform:uppercase;padding:7px 10px;left:0}}
td.us,thead th.us{{background:var(--accent-soft)}}
.chip{{display:inline-flex;align-items:center;gap:5px;font:500 12px var(--mono);padding:2px 7px;border-radius:999px;white-space:nowrap}}
.chip i{{width:7px;height:7px;border-radius:50%;background:currentColor;display:inline-block}}
.s-y{{color:var(--yes);background:var(--yes-bg)}} .s-p{{color:var(--part);background:var(--part-bg)}} .s-n{{color:var(--no);background:var(--no-bg)}}
.s-u{{color:var(--unk);background:var(--unk-bg)}} .s-na{{color:var(--na);background:transparent;border:1px dashed var(--line)}}
.note{{display:block;color:var(--muted);font-size:12px;line-height:1.35;margin-top:4px}}
.txt{{font:12px var(--mono);color:var(--ink)}}
.roadmap{{display:grid;gap:14px;grid-template-columns:repeat(auto-fit,minmax(260px,1fr))}}
.lane{{background:var(--surface);border:1px solid var(--line);border-radius:10px;padding:16px 18px;display:grid;gap:10px;align-content:start}}
.lane header p{{margin:4px 0 0;color:var(--muted);font-size:13px}}
.lane .ver{{font:600 12px var(--mono);color:var(--accent);letter-spacing:.04em}}
.lane h3{{font-size:17px;margin-top:4px}}
.lane ul{{list-style:none;margin:0;padding:0;display:grid;gap:10px}}
.lane li strong{{display:block;font-size:14px}} .lane li span{{color:var(--muted);font-size:13px}}
.lane-3,.lane-4{{background:transparent}} .lane-4 .ver{{color:var(--muted)}}
.hub{{display:grid;gap:6px;margin:0;padding:0;list-style:none}}
.hub li{{display:grid;grid-template-columns:90px 1fr;gap:10px;font-size:14px}}
.hub li b{{font:500 12px var(--mono);color:var(--muted);padding-top:2px}}
.sources{{columns:2 320px;gap:24px;margin:0;padding:0;list-style:none}}
.sources li{{break-inside:avoid;margin-bottom:12px;font-size:13px}}
.ver-note{{font:12px var(--mono);color:var(--muted)}}
a{{color:var(--accent)}} a:focus-visible{{outline:2px solid var(--accent);outline-offset:2px;border-radius:2px}}
.fine{{color:var(--muted);font-size:13px;max-width:80ch}}
@media (max-width:520px){{.wrap{{padding-inline:16px}}}}
</style>
<div class="wrap">
<header>
<div class="eyebrow">better-auth-saml-idp · feature comparison</div>
<h1>How a Better Auth SAML IdP compares with eleven others</h1>
<p class="lede">Shibboleth, SimpleSAMLphp and Keycloak as references; Zitadel, authentik, Logto and Ory Polis as modern open-source peers; Entra ID, Okta, Google Workspace and Auth0 as the commercial IdPs SPs are tested against. Every entry comes from the product's own documentation or source code.</p>
<div class="meta"><span>Checked {CHECKED}</span><span>11 products · {len(FEATURES)} features</span><span>“Not documented” ≠ “no”</span></div>
</header>
<div class="split">
<section class="panel lead"><h2>Where we lead</h2><ul>{"".join(f"<li><strong>{esc(t)}</strong>{esc(d)}</li>" for t,d in LEADS)}</ul>
<div class="score"><span>Our column: {count["y"]} yes</span><span>{count["p"]} partial</span><span>{count["n"]} no</span></div></section>
<section class="panel trail"><h2>Where we trail</h2><ul>{"".join(f"<li><strong>{esc(t)}</strong>{esc(d)}</li>" for t,d in TRAILS)}</ul>
<p class="fine" style="margin:12px 0 0">Each gap is on the roadmap below, in the order SPs and admins are most likely to hit it.</p></section>
</div>
<section style="display:grid;gap:12px">
<h2>Feature matrix</h2>
<div class="legend"><span class="chip s-y"><i></i>Yes</span><span class="chip s-p"><i></i>Partial</span><span class="chip s-n"><i></i>No</span><span class="chip s-u"><i></i>Not documented</span><span class="chip s-na"><i></i>n/a</span><span>Scroll sideways on small screens. Our column is shaded.</span></div>
<div class="tablebox" tabindex="0" aria-label="Feature matrix, scrollable">
<table>
<thead>
<tr class="g"><th></th>{"".join(f'<th colspan="{c}">{esc(g)}</th>' for g,c in head_groups)}</tr>
<tr class="p"><th>Feature</th>{"".join(f'<th class="{"us" if k=="us" else ""}">{esc(n)}<span class="v">{esc(v)}</span></th>' for k,n,g,v,src in PRODUCTS)}</tr>
</thead>
<tbody>{"".join(rows)}</tbody>
</table></div>
</section>
<section style="display:grid;gap:14px">
<div><h2>Roadmap</h2><p class="lede">What the comparison says to build next, in release order.</p></div>
<div class="roadmap">{roadmap_html}</div>
</section>
<div class="split">
<section class="panel"><h2>HubSpot, the first target SP</h2><ul class="hub">{"".join(f"<li><b>{esc(t)}</b><span>{esc(d)}</span></li>" for t,d in HUBSPOT)}</ul>
<p class="fine" style="margin:12px 0 0">Source: <a href="https://knowledge.hubspot.com/account-security/set-up-single-sign-on-sso">HubSpot SSO setup guide</a>. A live Cloudflare Access login has been verified; HubSpot itself has not yet been tested live.</p></section>
<section class="panel"><h2>Method</h2><p class="fine" style="margin:0">Three parallel reviews of vendor documentation on {CHECKED}, falling back to the default-branch source code for the open-source products where docs were silent. Our own column is backed by tests in the repository and a live login through Cloudflare Access. Corrections are welcome as issues on <a href="https://github.com/mmcintosh/better-auth-saml-idp">the repository</a>.</p></section>
</div>
<section style="display:grid;gap:12px"><h2>Sources</h2><ul class="sources">{sources_html}</ul></section>
</div>
'''
doc = ('<!doctype html><html lang="en"><head><meta charset="utf-8">'
       '<meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">'
       '<meta name="description" content="How better-auth-saml-idp compares with eleven SAML identity providers, with sources and roadmap.">'
       '<style>*,*::before,*::after{box-sizing:border-box}body{margin:0}img{max-width:100%}[hidden]{display:none!important}</style>'
       + page.split('<div class="wrap">', 1)[0] + "</head><body>"
       + '<div class="wrap">' + page.split('<div class="wrap">', 1)[1] + "</body></html>")
os.makedirs(os.path.join(ROOT, "docs/comparison"), exist_ok=True)
open(os.path.join(ROOT, "docs/comparison/index.html"), "w").write(doc)
open(os.path.join(ROOT, "docs/comparison/.artifact.html"), "w").write(page)  # body-only variant for the Claude artifact
print("wrote docs/comparison.md, docs/comparison/index.html, README roadmap")
